Fix logic in initialization examples for FTS3 plug-ins
The previous order is incorrect and causes Rucio to crash:

```
packages/rucio/transfertool/fts3_plugins.py", line 55, in __init__
    raise ValueError(f'Policy Algorithm {policy_algorithm} not found')
ValueError: Policy Algorithm activity not found
```